### ISSUE TITLE
rss feed broken

### ISSUE THREAD

**Issue by barakplasma** [RafaelGSS/blog#45]
I tried using the rss feed and it says it's not found.
https://blog.rafaelgss.com.br/rss

![image](https://github.com/RafaelGSS/blog/assets/62937/097840b6-aa32-4cee-91ff-4735d4d6fac6)

I made a new one with fetchrss.com
http://fetchrss.com/rss/6474617bafe4ff34332982826474fd06677a46535867c392.xml which targets https://blog.rafaelgss.dev/

I think you can fix it by swapping https://github.com/RafaelGSS/blog/blob/cbbb901724c6eb8fe320086dc5bae2cff0d572cc/lib/blog_web/controllers/rss_controller.ex#L5

**Comment by barakplasma** [comment]
I changed the rss feed to point to your https://blog.rafaelgss.dev/ domain.
http://fetchrss.com/rss/6474617bafe4ff34332982826474fd06677a46535867c392.xml

I don't want to make a PR, since I don't know elixer and wouldn't know how to test it.

**Comment by RafaelGSS** [comment]
Thanks!
